IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 11 AND FilterID = 6)
	INSERT INTO Int_FieldFilters VALUES (11,6)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 11 AND FilterID = 7)
	INSERT INTO Int_FieldFilters VALUES (11,7)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 12 AND FilterID = 6)
	INSERT INTO Int_FieldFilters VALUES (12,6)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 12 AND FilterID = 7)
	INSERT INTO Int_FieldFilters VALUES (12,7)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 13 AND FilterID = 6)
	INSERT INTO Int_FieldFilters VALUES (13,6)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 13 AND FilterID = 7)
	INSERT INTO Int_FieldFilters VALUES (13,7)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 23 AND FilterID = 6)
	INSERT INTO Int_FieldFilters VALUES (23,6)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 23 AND FilterID = 7)
	INSERT INTO Int_FieldFilters VALUES (23,7)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 24 AND FilterID = 6)
	INSERT INTO Int_FieldFilters VALUES (24,6)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 24 AND FilterID = 7)
	INSERT INTO Int_FieldFilters VALUES (24,7)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 25 AND FilterID = 6)
	INSERT INTO Int_FieldFilters VALUES (25,6)
IF NOT EXISTS (SELECT * FROM Int_FieldFilters WHERE FieldID = 25 AND FilterID = 7)
	INSERT INTO Int_FieldFilters VALUES (25,7)