//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCubeIntegration_BL.UFC_VehicleStock_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="UFC_VehicleStock_WS.ZVECHSTOCK")]
    public interface ZVECHSTOCK {
        
        // CODEGEN: Generating message contract since the operation ZFM_VECH_STOCK is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZVECHSTOCK:ZFM_VECH_STOCKRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse1 ZFM_VECH_STOCK(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZVECHSTOCK:ZFM_VECH_STOCKRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse1> ZFM_VECH_STOCKAsync(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_VECH_STOCK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vEHCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VEHCODE {
            get {
                return this.vEHCODEField;
            }
            set {
                this.vEHCODEField = value;
                this.RaisePropertyChanged("VEHCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZVECSTOCK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vEHCODEField;
        
        private string iCODEField;
        
        private string uOMField;
        
        private string eXPIRY_DATEField;
        
        private string bATCH_NOField;
        
        private decimal qTYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VEHCODE {
            get {
                return this.vEHCODEField;
            }
            set {
                this.vEHCODEField = value;
                this.RaisePropertyChanged("VEHCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ICODE {
            get {
                return this.iCODEField;
            }
            set {
                this.iCODEField = value;
                this.RaisePropertyChanged("ICODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EXPIRY_DATE {
            get {
                return this.eXPIRY_DATEField;
            }
            set {
                this.eXPIRY_DATEField = value;
                this.RaisePropertyChanged("EXPIRY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BATCH_NO {
            get {
                return this.bATCH_NOField;
            }
            set {
                this.bATCH_NOField = value;
                this.RaisePropertyChanged("BATCH_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
                this.RaisePropertyChanged("QTY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_VECH_STOCKResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mESSAGEField;
        
        private ZVECSTOCK[] vECHSTOCKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZVECSTOCK[] VECHSTOCK {
            get {
                return this.vECHSTOCKField;
            }
            set {
                this.vECHSTOCKField = value;
                this.RaisePropertyChanged("VECHSTOCK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_VECH_STOCKRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCK ZFM_VECH_STOCK;
        
        public ZFM_VECH_STOCKRequest() {
        }
        
        public ZFM_VECH_STOCKRequest(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCK ZFM_VECH_STOCK) {
            this.ZFM_VECH_STOCK = ZFM_VECH_STOCK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_VECH_STOCKResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse ZFM_VECH_STOCKResponse;
        
        public ZFM_VECH_STOCKResponse1() {
        }
        
        public ZFM_VECH_STOCKResponse1(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse ZFM_VECH_STOCKResponse) {
            this.ZFM_VECH_STOCKResponse = ZFM_VECH_STOCKResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZVECHSTOCKChannel : InCubeIntegration_BL.UFC_VehicleStock_WS.ZVECHSTOCK, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZVECHSTOCKClient : System.ServiceModel.ClientBase<InCubeIntegration_BL.UFC_VehicleStock_WS.ZVECHSTOCK>, InCubeIntegration_BL.UFC_VehicleStock_WS.ZVECHSTOCK {
        
        public ZVECHSTOCKClient() {
        }
        
        public ZVECHSTOCKClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZVECHSTOCKClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZVECHSTOCKClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZVECHSTOCKClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse1 InCubeIntegration_BL.UFC_VehicleStock_WS.ZVECHSTOCK.ZFM_VECH_STOCK(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest request) {
            return base.Channel.ZFM_VECH_STOCK(request);
        }
        
        public InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse ZFM_VECH_STOCK(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCK ZFM_VECH_STOCK1) {
            InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest inValue = new InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest();
            inValue.ZFM_VECH_STOCK = ZFM_VECH_STOCK1;
            InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse1 retVal = ((InCubeIntegration_BL.UFC_VehicleStock_WS.ZVECHSTOCK)(this)).ZFM_VECH_STOCK(inValue);
            return retVal.ZFM_VECH_STOCKResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse1> InCubeIntegration_BL.UFC_VehicleStock_WS.ZVECHSTOCK.ZFM_VECH_STOCKAsync(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest request) {
            return base.Channel.ZFM_VECH_STOCKAsync(request);
        }
        
        public System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKResponse1> ZFM_VECH_STOCKAsync(InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCK ZFM_VECH_STOCK) {
            InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest inValue = new InCubeIntegration_BL.UFC_VehicleStock_WS.ZFM_VECH_STOCKRequest();
            inValue.ZFM_VECH_STOCK = ZFM_VECH_STOCK;
            return ((InCubeIntegration_BL.UFC_VehicleStock_WS.ZVECHSTOCK)(this)).ZFM_VECH_STOCKAsync(inValue);
        }
    }
}
