//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCubeIntegration_BL.UFC_Collections_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="UFC_Collections_WS.zinvan_integration1")]
    public interface zinvan_integration1 {
        
        // CODEGEN: Generating message contract since the operation ZINVAN_COLLECTION_POST_C1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zinvan_integration1:ZINVAN_COLLECTION_POST" +
            "_C1Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response1 ZINVAN_COLLECTION_POST_C1(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zinvan_integration1:ZINVAN_COLLECTION_POST" +
            "_C1Request", ReplyAction="*")]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response1> ZINVAN_COLLECTION_POST_C1Async(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZINVAN_COLLECTION_POST_C1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZIN_VAN_COLLECTION[] gT_COLLECTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZIN_VAN_COLLECTION[] GT_COLLECTION {
            get {
                return this.gT_COLLECTIONField;
            }
            set {
                this.gT_COLLECTIONField = value;
                this.RaisePropertyChanged("GT_COLLECTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZIN_VAN_COLLECTION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zPAY_NUMField;
        
        private string zVAN_INVOICEField;
        
        private string zBILL_TOField;
        
        private string zSHIP_TOField;
        
        private string zPAY_DATEField;
        
        private string zINV_DATEField;
        
        private string zSALEMAN_CODEField;
        
        private string zPAID_AMOUNTField;
        
        private string zPAY_TYPEField;
        
        private string zCHEQUE_NOField;
        
        private string zCHEQUE_DATEField;
        
        private string zBANK_CODEField;
        
        private string zINV_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZPAY_NUM {
            get {
                return this.zPAY_NUMField;
            }
            set {
                this.zPAY_NUMField = value;
                this.RaisePropertyChanged("ZPAY_NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZVAN_INVOICE {
            get {
                return this.zVAN_INVOICEField;
            }
            set {
                this.zVAN_INVOICEField = value;
                this.RaisePropertyChanged("ZVAN_INVOICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZBILL_TO {
            get {
                return this.zBILL_TOField;
            }
            set {
                this.zBILL_TOField = value;
                this.RaisePropertyChanged("ZBILL_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZSHIP_TO {
            get {
                return this.zSHIP_TOField;
            }
            set {
                this.zSHIP_TOField = value;
                this.RaisePropertyChanged("ZSHIP_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZPAY_DATE {
            get {
                return this.zPAY_DATEField;
            }
            set {
                this.zPAY_DATEField = value;
                this.RaisePropertyChanged("ZPAY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZINV_DATE {
            get {
                return this.zINV_DATEField;
            }
            set {
                this.zINV_DATEField = value;
                this.RaisePropertyChanged("ZINV_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZSALEMAN_CODE {
            get {
                return this.zSALEMAN_CODEField;
            }
            set {
                this.zSALEMAN_CODEField = value;
                this.RaisePropertyChanged("ZSALEMAN_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZPAID_AMOUNT {
            get {
                return this.zPAID_AMOUNTField;
            }
            set {
                this.zPAID_AMOUNTField = value;
                this.RaisePropertyChanged("ZPAID_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZPAY_TYPE {
            get {
                return this.zPAY_TYPEField;
            }
            set {
                this.zPAY_TYPEField = value;
                this.RaisePropertyChanged("ZPAY_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZCHEQUE_NO {
            get {
                return this.zCHEQUE_NOField;
            }
            set {
                this.zCHEQUE_NOField = value;
                this.RaisePropertyChanged("ZCHEQUE_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZCHEQUE_DATE {
            get {
                return this.zCHEQUE_DATEField;
            }
            set {
                this.zCHEQUE_DATEField = value;
                this.RaisePropertyChanged("ZCHEQUE_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZBANK_CODE {
            get {
                return this.zBANK_CODEField;
            }
            set {
                this.zBANK_CODEField = value;
                this.RaisePropertyChanged("ZBANK_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZINV_TYPE {
            get {
                return this.zINV_TYPEField;
            }
            set {
                this.zINV_TYPEField = value;
                this.RaisePropertyChanged("ZINV_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFI_COLL_STATUS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zVAN_INVOICEField;
        
        private string tYPEField;
        
        private string sTATUS_MESSField;
        
        private string zPAY_NUMField;
        
        private string zBILL_TOField;
        
        private string zSHIP_TOField;
        
        private string zPAY_DATEField;
        
        private string zINV_DATEField;
        
        private string zSALEMAN_CODEField;
        
        private string zPAID_AMOUNTField;
        
        private string zPAY_TYPEField;
        
        private string zCHEQUE_NOField;
        
        private string zCHEQUE_DATEField;
        
        private string zBANK_CODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZVAN_INVOICE {
            get {
                return this.zVAN_INVOICEField;
            }
            set {
                this.zVAN_INVOICEField = value;
                this.RaisePropertyChanged("ZVAN_INVOICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string STATUS_MESS {
            get {
                return this.sTATUS_MESSField;
            }
            set {
                this.sTATUS_MESSField = value;
                this.RaisePropertyChanged("STATUS_MESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZPAY_NUM {
            get {
                return this.zPAY_NUMField;
            }
            set {
                this.zPAY_NUMField = value;
                this.RaisePropertyChanged("ZPAY_NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZBILL_TO {
            get {
                return this.zBILL_TOField;
            }
            set {
                this.zBILL_TOField = value;
                this.RaisePropertyChanged("ZBILL_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZSHIP_TO {
            get {
                return this.zSHIP_TOField;
            }
            set {
                this.zSHIP_TOField = value;
                this.RaisePropertyChanged("ZSHIP_TO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZPAY_DATE {
            get {
                return this.zPAY_DATEField;
            }
            set {
                this.zPAY_DATEField = value;
                this.RaisePropertyChanged("ZPAY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZINV_DATE {
            get {
                return this.zINV_DATEField;
            }
            set {
                this.zINV_DATEField = value;
                this.RaisePropertyChanged("ZINV_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZSALEMAN_CODE {
            get {
                return this.zSALEMAN_CODEField;
            }
            set {
                this.zSALEMAN_CODEField = value;
                this.RaisePropertyChanged("ZSALEMAN_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZPAID_AMOUNT {
            get {
                return this.zPAID_AMOUNTField;
            }
            set {
                this.zPAID_AMOUNTField = value;
                this.RaisePropertyChanged("ZPAID_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZPAY_TYPE {
            get {
                return this.zPAY_TYPEField;
            }
            set {
                this.zPAY_TYPEField = value;
                this.RaisePropertyChanged("ZPAY_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZCHEQUE_NO {
            get {
                return this.zCHEQUE_NOField;
            }
            set {
                this.zCHEQUE_NOField = value;
                this.RaisePropertyChanged("ZCHEQUE_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZCHEQUE_DATE {
            get {
                return this.zCHEQUE_DATEField;
            }
            set {
                this.zCHEQUE_DATEField = value;
                this.RaisePropertyChanged("ZCHEQUE_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZBANK_CODE {
            get {
                return this.zBANK_CODEField;
            }
            set {
                this.zBANK_CODEField = value;
                this.RaisePropertyChanged("ZBANK_CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZINVAN_COLLECTION_POST_C1Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZFI_COLL_STATUS[] gT_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZFI_COLL_STATUS[] GT_STATUS {
            get {
                return this.gT_STATUSField;
            }
            set {
                this.gT_STATUSField = value;
                this.RaisePropertyChanged("GT_STATUS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZINVAN_COLLECTION_POST_C1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1 ZINVAN_COLLECTION_POST_C1;
        
        public ZINVAN_COLLECTION_POST_C1Request() {
        }
        
        public ZINVAN_COLLECTION_POST_C1Request(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1 ZINVAN_COLLECTION_POST_C1) {
            this.ZINVAN_COLLECTION_POST_C1 = ZINVAN_COLLECTION_POST_C1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZINVAN_COLLECTION_POST_C1Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response ZINVAN_COLLECTION_POST_C1Response;
        
        public ZINVAN_COLLECTION_POST_C1Response1() {
        }
        
        public ZINVAN_COLLECTION_POST_C1Response1(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response ZINVAN_COLLECTION_POST_C1Response) {
            this.ZINVAN_COLLECTION_POST_C1Response = ZINVAN_COLLECTION_POST_C1Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface zinvan_integration1Channel : InCubeIntegration_BL.UFC_Collections_WS.zinvan_integration1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class zinvan_integration1Client : System.ServiceModel.ClientBase<InCubeIntegration_BL.UFC_Collections_WS.zinvan_integration1>, InCubeIntegration_BL.UFC_Collections_WS.zinvan_integration1 {
        
        public zinvan_integration1Client() {
        }
        
        public zinvan_integration1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public zinvan_integration1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zinvan_integration1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public zinvan_integration1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response1 InCubeIntegration_BL.UFC_Collections_WS.zinvan_integration1.ZINVAN_COLLECTION_POST_C1(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request request) {
            return base.Channel.ZINVAN_COLLECTION_POST_C1(request);
        }
        
        public InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response ZINVAN_COLLECTION_POST_C1(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1 ZINVAN_COLLECTION_POST_C11) {
            InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request inValue = new InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request();
            inValue.ZINVAN_COLLECTION_POST_C1 = ZINVAN_COLLECTION_POST_C11;
            InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response1 retVal = ((InCubeIntegration_BL.UFC_Collections_WS.zinvan_integration1)(this)).ZINVAN_COLLECTION_POST_C1(inValue);
            return retVal.ZINVAN_COLLECTION_POST_C1Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response1> InCubeIntegration_BL.UFC_Collections_WS.zinvan_integration1.ZINVAN_COLLECTION_POST_C1Async(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request request) {
            return base.Channel.ZINVAN_COLLECTION_POST_C1Async(request);
        }
        
        public System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Response1> ZINVAN_COLLECTION_POST_C1Async(InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1 ZINVAN_COLLECTION_POST_C1) {
            InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request inValue = new InCubeIntegration_BL.UFC_Collections_WS.ZINVAN_COLLECTION_POST_C1Request();
            inValue.ZINVAN_COLLECTION_POST_C1 = ZINVAN_COLLECTION_POST_C1;
            return ((InCubeIntegration_BL.UFC_Collections_WS.zinvan_integration1)(this)).ZINVAN_COLLECTION_POST_C1Async(inValue);
        }
    }
}
