//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCubeIntegration_BL.UFC_LoadRequest_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS")]
    public interface ZMM_LOAD_REQ_POST_RET_WS {
        
        // CODEGEN: Generating message contract since the operation ZMM_INV_LOAD_POST_WS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZMM_LOAD_REQ_POST_RET_WS:ZMM_INV_LOAD_POST" +
            "_WSRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse1 ZMM_INV_LOAD_POST_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZMM_LOAD_REQ_POST_RET_WS:ZMM_INV_LOAD_POST" +
            "_WSRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse1> ZMM_INV_LOAD_POST_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest request);
        
        // CODEGEN: Generating message contract since the operation ZMM_INV_LOAD_REQ_WS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZMM_LOAD_REQ_POST_RET_WS:ZMM_INV_LOAD_REQ_" +
            "WSRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse1 ZMM_INV_LOAD_REQ_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZMM_LOAD_REQ_POST_RET_WS:ZMM_INV_LOAD_REQ_" +
            "WSRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse1> ZMM_INV_LOAD_REQ_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest request);
        
        // CODEGEN: Generating message contract since the operation ZMM_INV_LOAD_RET_WS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZMM_LOAD_REQ_POST_RET_WS:ZMM_INV_LOAD_RET_" +
            "WSRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse1 ZMM_INV_LOAD_RET_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZMM_LOAD_REQ_POST_RET_WS:ZMM_INV_LOAD_RET_" +
            "WSRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse1> ZMM_INV_LOAD_RET_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_POST_WS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sTATUSField;
        
        private string tRNUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRNUM {
            get {
                return this.tRNUMField;
            }
            set {
                this.tRNUMField = value;
                this.RaisePropertyChanged("TRNUM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_ITEM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tRNUMField;
        
        private byte lNUMBField;
        
        private string iCODEField;
        
        private string uOMField;
        
        private decimal qTYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TRNUM {
            get {
                return this.tRNUMField;
            }
            set {
                this.tRNUMField = value;
                this.RaisePropertyChanged("TRNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public byte LNUMB {
            get {
                return this.lNUMBField;
            }
            set {
                this.lNUMBField = value;
                this.RaisePropertyChanged("LNUMB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ICODE {
            get {
                return this.iCODEField;
            }
            set {
                this.iCODEField = value;
                this.RaisePropertyChanged("ICODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
                this.RaisePropertyChanged("QTY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tRNUMField;
        
        private string vEH_NOField;
        
        private string lGORTField;
        
        private string tR_TYPEField;
        
        private string tR_STATField;
        
        private string tR_DATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TRNUM {
            get {
                return this.tRNUMField;
            }
            set {
                this.tRNUMField = value;
                this.RaisePropertyChanged("TRNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VEH_NO {
            get {
                return this.vEH_NOField;
            }
            set {
                this.vEH_NOField = value;
                this.RaisePropertyChanged("VEH_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
                this.RaisePropertyChanged("LGORT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TR_TYPE {
            get {
                return this.tR_TYPEField;
            }
            set {
                this.tR_TYPEField = value;
                this.RaisePropertyChanged("TR_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TR_STAT {
            get {
                return this.tR_STATField;
            }
            set {
                this.tR_STATField = value;
                this.RaisePropertyChanged("TR_STAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TR_DATE {
            get {
                return this.tR_DATEField;
            }
            set {
                this.tR_DATEField = value;
                this.RaisePropertyChanged("TR_DATE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mAT_DOCField;
        
        private string iCODEField;
        
        private decimal qTYField;
        
        private string uOMField;
        
        private string mSGTYField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MAT_DOC {
            get {
                return this.mAT_DOCField;
            }
            set {
                this.mAT_DOCField = value;
                this.RaisePropertyChanged("MAT_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ICODE {
            get {
                return this.iCODEField;
            }
            set {
                this.iCODEField = value;
                this.RaisePropertyChanged("ICODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
                this.RaisePropertyChanged("QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MSGTY {
            get {
                return this.mSGTYField;
            }
            set {
                this.mSGTYField = value;
                this.RaisePropertyChanged("MSGTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_POST_WSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMM_INV_LOAD_RETURN[] eT_LOGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMM_INV_LOAD_RETURN[] ET_LOG {
            get {
                return this.eT_LOGField;
            }
            set {
                this.eT_LOGField = value;
                this.RaisePropertyChanged("ET_LOG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_INV_LOAD_POST_WSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WS ZMM_INV_LOAD_POST_WS;
        
        public ZMM_INV_LOAD_POST_WSRequest() {
        }
        
        public ZMM_INV_LOAD_POST_WSRequest(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WS ZMM_INV_LOAD_POST_WS) {
            this.ZMM_INV_LOAD_POST_WS = ZMM_INV_LOAD_POST_WS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_INV_LOAD_POST_WSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse ZMM_INV_LOAD_POST_WSResponse;
        
        public ZMM_INV_LOAD_POST_WSResponse1() {
        }
        
        public ZMM_INV_LOAD_POST_WSResponse1(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse ZMM_INV_LOAD_POST_WSResponse) {
            this.ZMM_INV_LOAD_POST_WSResponse = ZMM_INV_LOAD_POST_WSResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_REQ_WS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMM_INV_LOAD eT_HEADField;
        
        private ZMM_INV_LOAD_ITEM[] eT_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZMM_INV_LOAD ET_HEAD {
            get {
                return this.eT_HEADField;
            }
            set {
                this.eT_HEADField = value;
                this.RaisePropertyChanged("ET_HEAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMM_INV_LOAD_ITEM[] ET_ITEM {
            get {
                return this.eT_ITEMField;
            }
            set {
                this.eT_ITEMField = value;
                this.RaisePropertyChanged("ET_ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_REQ_WSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMM_INV_LOAD_RETURN[] eT_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMM_INV_LOAD_RETURN[] ET_ERROR {
            get {
                return this.eT_ERRORField;
            }
            set {
                this.eT_ERRORField = value;
                this.RaisePropertyChanged("ET_ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_INV_LOAD_REQ_WSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WS ZMM_INV_LOAD_REQ_WS;
        
        public ZMM_INV_LOAD_REQ_WSRequest() {
        }
        
        public ZMM_INV_LOAD_REQ_WSRequest(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WS ZMM_INV_LOAD_REQ_WS) {
            this.ZMM_INV_LOAD_REQ_WS = ZMM_INV_LOAD_REQ_WS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_INV_LOAD_REQ_WSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse ZMM_INV_LOAD_REQ_WSResponse;
        
        public ZMM_INV_LOAD_REQ_WSResponse1() {
        }
        
        public ZMM_INV_LOAD_REQ_WSResponse1(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse ZMM_INV_LOAD_REQ_WSResponse) {
            this.ZMM_INV_LOAD_REQ_WSResponse = ZMM_INV_LOAD_REQ_WSResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_RET_WS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMM_INV_LOAD eT_HEADField;
        
        private ZMM_INV_LOAD_ITEM[] eT_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZMM_INV_LOAD ET_HEAD {
            get {
                return this.eT_HEADField;
            }
            set {
                this.eT_HEADField = value;
                this.RaisePropertyChanged("ET_HEAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMM_INV_LOAD_ITEM[] ET_ITEM {
            get {
                return this.eT_ITEMField;
            }
            set {
                this.eT_ITEMField = value;
                this.RaisePropertyChanged("ET_ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_INV_LOAD_RET_WSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZMM_INV_LOAD_RETURN[] eT_ERRORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMM_INV_LOAD_RETURN[] ET_ERROR {
            get {
                return this.eT_ERRORField;
            }
            set {
                this.eT_ERRORField = value;
                this.RaisePropertyChanged("ET_ERROR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_INV_LOAD_RET_WSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WS ZMM_INV_LOAD_RET_WS;
        
        public ZMM_INV_LOAD_RET_WSRequest() {
        }
        
        public ZMM_INV_LOAD_RET_WSRequest(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WS ZMM_INV_LOAD_RET_WS) {
            this.ZMM_INV_LOAD_RET_WS = ZMM_INV_LOAD_RET_WS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_INV_LOAD_RET_WSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse ZMM_INV_LOAD_RET_WSResponse;
        
        public ZMM_INV_LOAD_RET_WSResponse1() {
        }
        
        public ZMM_INV_LOAD_RET_WSResponse1(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse ZMM_INV_LOAD_RET_WSResponse) {
            this.ZMM_INV_LOAD_RET_WSResponse = ZMM_INV_LOAD_RET_WSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZMM_LOAD_REQ_POST_RET_WSChannel : InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZMM_LOAD_REQ_POST_RET_WSClient : System.ServiceModel.ClientBase<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS>, InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS {
        
        public ZMM_LOAD_REQ_POST_RET_WSClient() {
        }
        
        public ZMM_LOAD_REQ_POST_RET_WSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZMM_LOAD_REQ_POST_RET_WSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZMM_LOAD_REQ_POST_RET_WSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZMM_LOAD_REQ_POST_RET_WSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse1 InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS.ZMM_INV_LOAD_POST_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest request) {
            return base.Channel.ZMM_INV_LOAD_POST_WS(request);
        }
        
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse ZMM_INV_LOAD_POST_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WS ZMM_INV_LOAD_POST_WS1) {
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest inValue = new InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest();
            inValue.ZMM_INV_LOAD_POST_WS = ZMM_INV_LOAD_POST_WS1;
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse1 retVal = ((InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS)(this)).ZMM_INV_LOAD_POST_WS(inValue);
            return retVal.ZMM_INV_LOAD_POST_WSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse1> InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS.ZMM_INV_LOAD_POST_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest request) {
            return base.Channel.ZMM_INV_LOAD_POST_WSAsync(request);
        }
        
        public System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSResponse1> ZMM_INV_LOAD_POST_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WS ZMM_INV_LOAD_POST_WS) {
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest inValue = new InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_POST_WSRequest();
            inValue.ZMM_INV_LOAD_POST_WS = ZMM_INV_LOAD_POST_WS;
            return ((InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS)(this)).ZMM_INV_LOAD_POST_WSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse1 InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS.ZMM_INV_LOAD_REQ_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest request) {
            return base.Channel.ZMM_INV_LOAD_REQ_WS(request);
        }
        
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse ZMM_INV_LOAD_REQ_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WS ZMM_INV_LOAD_REQ_WS1) {
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest inValue = new InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest();
            inValue.ZMM_INV_LOAD_REQ_WS = ZMM_INV_LOAD_REQ_WS1;
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse1 retVal = ((InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS)(this)).ZMM_INV_LOAD_REQ_WS(inValue);
            return retVal.ZMM_INV_LOAD_REQ_WSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse1> InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS.ZMM_INV_LOAD_REQ_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest request) {
            return base.Channel.ZMM_INV_LOAD_REQ_WSAsync(request);
        }
        
        public System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSResponse1> ZMM_INV_LOAD_REQ_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WS ZMM_INV_LOAD_REQ_WS) {
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest inValue = new InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_REQ_WSRequest();
            inValue.ZMM_INV_LOAD_REQ_WS = ZMM_INV_LOAD_REQ_WS;
            return ((InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS)(this)).ZMM_INV_LOAD_REQ_WSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse1 InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS.ZMM_INV_LOAD_RET_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest request) {
            return base.Channel.ZMM_INV_LOAD_RET_WS(request);
        }
        
        public InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse ZMM_INV_LOAD_RET_WS(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WS ZMM_INV_LOAD_RET_WS1) {
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest inValue = new InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest();
            inValue.ZMM_INV_LOAD_RET_WS = ZMM_INV_LOAD_RET_WS1;
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse1 retVal = ((InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS)(this)).ZMM_INV_LOAD_RET_WS(inValue);
            return retVal.ZMM_INV_LOAD_RET_WSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse1> InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS.ZMM_INV_LOAD_RET_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest request) {
            return base.Channel.ZMM_INV_LOAD_RET_WSAsync(request);
        }
        
        public System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSResponse1> ZMM_INV_LOAD_RET_WSAsync(InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WS ZMM_INV_LOAD_RET_WS) {
            InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest inValue = new InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_INV_LOAD_RET_WSRequest();
            inValue.ZMM_INV_LOAD_RET_WS = ZMM_INV_LOAD_RET_WS;
            return ((InCubeIntegration_BL.UFC_LoadRequest_WS.ZMM_LOAD_REQ_POST_RET_WS)(this)).ZMM_INV_LOAD_RET_WSAsync(inValue);
        }
    }
}
