//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCubeIntegration_BL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://spouxp2d:50200/XISOAPAdapter/MessageServlet?channel=:BS_PALM_05:CC_PALM_SO" +
            "AP_SND&version=3.0&Sender.Service=CC_PALM_SOAP_SND&Interface=ITF_O_S_EnvRecArqPa" +
            "lm%5EBS_PALM_05")]
        public string InCubeIntegration_BL_BRF_SAP_WS_ITF_O_S_EnvRecArqPalmService {
            get {
                return ((string)(this["InCubeIntegration_BL_BRF_SAP_WS_ITF_O_S_EnvRecArqPalmService"]));
            }
        }
    }
}
