//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InCubeIntegration_BL.BRF_SAP_WS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ITF_O_S_EnvRecArqPalmBinding", Namespace="http://www.EnviaRecebeArquivoPalm.com.br")]
    public partial class ITF_O_S_EnvRecArqPalmService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ITF_O_S_EnvRecArqPalmOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ITF_O_S_EnvRecArqPalmService() {
            this.Url = global::InCubeIntegration_BL.Properties.Settings.Default.InCubeIntegration_BL_BRF_SAP_WS_ITF_O_S_EnvRecArqPalmService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
       // public event ITF_O_S_EnvRecArqPalmCompletedEventHandler ITF_O_S_EnvRecArqPalmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MTP_EnvRecArqPalm_Resp", Namespace="http://www.EnviaRecebeArquivoPalm.com.br")]
        public DTP_EnvRecArqPalm_Resp ITF_O_S_EnvRecArqPalm([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.EnviaRecebeArquivoPalm.com.br")] DTP_EnvRecArqPalm_Req MTP_EnvRecArqPalm_Req) {
            object[] results = this.Invoke("ITF_O_S_EnvRecArqPalm", new object[] {
                        MTP_EnvRecArqPalm_Req});
            return ((DTP_EnvRecArqPalm_Resp)(results[0]));
        }
        
        /// <remarks/>
       /* public void ITF_O_S_EnvRecArqPalmAsync(DTP_EnvRecArqPalm_Req MTP_EnvRecArqPalm_Req) {
            this.ITF_O_S_EnvRecArqPalmAsync(MTP_EnvRecArqPalm_Req, null);
        }*/
        
        /// <remarks/>
       /* public void ITF_O_S_EnvRecArqPalmAsync(DTP_EnvRecArqPalm_Req MTP_EnvRecArqPalm_Req, object userState) {
            if ((this.ITF_O_S_EnvRecArqPalmOperationCompleted == null)) {
                this.ITF_O_S_EnvRecArqPalmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnITF_O_S_EnvRecArqPalmOperationCompleted);
            }
            this.InvokeAsync("ITF_O_S_EnvRecArqPalm", new object[] {
                        MTP_EnvRecArqPalm_Req}, this.ITF_O_S_EnvRecArqPalmOperationCompleted, userState);
        }*/
        
       /* private void OnITF_O_S_EnvRecArqPalmOperationCompleted(object arg) {
            if ((this.ITF_O_S_EnvRecArqPalmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ITF_O_S_EnvRecArqPalmCompleted(this, new ITF_O_S_EnvRecArqPalmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }*/
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.EnviaRecebeArquivoPalm.com.br")]
    public partial class DTP_EnvRecArqPalm_Req {
        
        private string caixaPostalField;
        
        private string tipoArquivoField;
        
        private string eventoField;
        
        private string numLinhasField;
        
        private string iMEIField;
        
        private string serialField;
        
        private string versaoField;
        
        private DTP_EnvRecArqPalm_ReqT_Dados_IN[] t_Dados_INField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CaixaPostal {
            get {
                return this.caixaPostalField;
            }
            set {
                this.caixaPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipoArquivo {
            get {
                return this.tipoArquivoField;
            }
            set {
                this.tipoArquivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string NumLinhas {
            get {
                return this.numLinhasField;
            }
            set {
                this.numLinhasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IMEI {
            get {
                return this.iMEIField;
            }
            set {
                this.iMEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_Dados_IN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_EnvRecArqPalm_ReqT_Dados_IN[] T_Dados_IN {
            get {
                return this.t_Dados_INField;
            }
            set {
                this.t_Dados_INField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.EnviaRecebeArquivoPalm.com.br")]
    public partial class DTP_EnvRecArqPalm_ReqT_Dados_IN {
        
        private string dadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.EnviaRecebeArquivoPalm.com.br")]
    public partial class DTP_EnvRecArqPalm_Resp {
        
        private string erroField;
        
        private string mensagemField;
        
        private string nomeArqField;
        
        private string numLinhasField;
        
        private DTP_EnvRecArqPalm_RespT_Dados_OUT[] t_Dados_OUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomeArq {
            get {
                return this.nomeArqField;
            }
            set {
                this.nomeArqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string NumLinhas {
            get {
                return this.numLinhasField;
            }
            set {
                this.numLinhasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("T_Dados_OUT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_EnvRecArqPalm_RespT_Dados_OUT[] T_Dados_OUT {
            get {
                return this.t_Dados_OUTField;
            }
            set {
                this.t_Dados_OUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.EnviaRecebeArquivoPalm.com.br")]
    public partial class DTP_EnvRecArqPalm_RespT_Dados_OUT {
        
        private string dadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
            }
        }
    }
    
    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    /*public 
        void ITF_O_S_EnvRecArqPalmCompletedEventHandler(object sender, ITF_O_S_EnvRecArqPalmCompletedEventArgs e);*/
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ITF_O_S_EnvRecArqPalmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ITF_O_S_EnvRecArqPalmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTP_EnvRecArqPalm_Resp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTP_EnvRecArqPalm_Resp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591