//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCubeIntegration_BL.UFC_SalesReturns_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG")]
    public interface ZSD_Invan_so_to_invoice_FG {
        
        // CODEGEN: Generating message contract since the operation ZsdInvanSoToInvoicePost is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZSD_Invan_so_to_invoice_FG:ZsdIn" +
            "vanSoToInvoicePostRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse1 ZsdInvanSoToInvoicePost(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZSD_Invan_so_to_invoice_FG:ZsdIn" +
            "vanSoToInvoicePostRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse1> ZsdInvanSoToInvoicePostAsync(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsdInvanSoToInvoicePost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZinvanInvoiceHeader[] etHeadField;
        
        private ZinvanInvoiceItems[] etItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinvanInvoiceHeader[] EtHead {
            get {
                return this.etHeadField;
            }
            set {
                this.etHeadField = value;
                this.RaisePropertyChanged("EtHead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinvanInvoiceItems[] EtItem {
            get {
                return this.etItemField;
            }
            set {
                this.etItemField = value;
                this.RaisePropertyChanged("EtItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinvanInvoiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trnumField;
        
        private string bcodeField;
        
        private string scodeField;
        
        private byte blartField;
        
        private string tdateField;
        
        private string smcodeField;
        
        private string lcodeField;
        
        private string lponoField;
        
        private decimal inamtField;
        
        private decimal hdiscField;
        
        private decimal reamtField;
        
        private string rtrnuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trnum {
            get {
                return this.trnumField;
            }
            set {
                this.trnumField = value;
                this.RaisePropertyChanged("Trnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Bcode {
            get {
                return this.bcodeField;
            }
            set {
                this.bcodeField = value;
                this.RaisePropertyChanged("Bcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Scode {
            get {
                return this.scodeField;
            }
            set {
                this.scodeField = value;
                this.RaisePropertyChanged("Scode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public byte Blart {
            get {
                return this.blartField;
            }
            set {
                this.blartField = value;
                this.RaisePropertyChanged("Blart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Tdate {
            get {
                return this.tdateField;
            }
            set {
                this.tdateField = value;
                this.RaisePropertyChanged("Tdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Smcode {
            get {
                return this.smcodeField;
            }
            set {
                this.smcodeField = value;
                this.RaisePropertyChanged("Smcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Lcode {
            get {
                return this.lcodeField;
            }
            set {
                this.lcodeField = value;
                this.RaisePropertyChanged("Lcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Lpono {
            get {
                return this.lponoField;
            }
            set {
                this.lponoField = value;
                this.RaisePropertyChanged("Lpono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Inamt {
            get {
                return this.inamtField;
            }
            set {
                this.inamtField = value;
                this.RaisePropertyChanged("Inamt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Hdisc {
            get {
                return this.hdiscField;
            }
            set {
                this.hdiscField = value;
                this.RaisePropertyChanged("Hdisc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Reamt {
            get {
                return this.reamtField;
            }
            set {
                this.reamtField = value;
                this.RaisePropertyChanged("Reamt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Rtrnu {
            get {
                return this.rtrnuField;
            }
            set {
                this.rtrnuField = value;
                this.RaisePropertyChanged("Rtrnu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsdInvoiceErr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vbelnField;
        
        private string msgtyField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
                this.RaisePropertyChanged("Vbeln");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Msgty {
            get {
                return this.msgtyField;
            }
            set {
                this.msgtyField = value;
                this.RaisePropertyChanged("Msgty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinvanInvoiceItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trnumField;
        
        private string bcodeField;
        
        private string scodeField;
        
        private byte lnumbField;
        
        private string icodeField;
        
        private string uomField;
        
        private byte istatusField;
        
        private decimal sqtyField;
        
        private decimal rqtyField;
        
        private decimal focqtyField;
        
        private decimal freeqtyField;
        
        private decimal priceField;
        
        private decimal idiscField;
        
        private decimal ttlamtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trnum {
            get {
                return this.trnumField;
            }
            set {
                this.trnumField = value;
                this.RaisePropertyChanged("Trnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Bcode {
            get {
                return this.bcodeField;
            }
            set {
                this.bcodeField = value;
                this.RaisePropertyChanged("Bcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Scode {
            get {
                return this.scodeField;
            }
            set {
                this.scodeField = value;
                this.RaisePropertyChanged("Scode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public byte Lnumb {
            get {
                return this.lnumbField;
            }
            set {
                this.lnumbField = value;
                this.RaisePropertyChanged("Lnumb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Icode {
            get {
                return this.icodeField;
            }
            set {
                this.icodeField = value;
                this.RaisePropertyChanged("Icode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
                this.RaisePropertyChanged("Uom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public byte Istatus {
            get {
                return this.istatusField;
            }
            set {
                this.istatusField = value;
                this.RaisePropertyChanged("Istatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Sqty {
            get {
                return this.sqtyField;
            }
            set {
                this.sqtyField = value;
                this.RaisePropertyChanged("Sqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Rqty {
            get {
                return this.rqtyField;
            }
            set {
                this.rqtyField = value;
                this.RaisePropertyChanged("Rqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Focqty {
            get {
                return this.focqtyField;
            }
            set {
                this.focqtyField = value;
                this.RaisePropertyChanged("Focqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Freeqty {
            get {
                return this.freeqtyField;
            }
            set {
                this.freeqtyField = value;
                this.RaisePropertyChanged("Freeqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Idisc {
            get {
                return this.idiscField;
            }
            set {
                this.idiscField = value;
                this.RaisePropertyChanged("Idisc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal Ttlamt {
            get {
                return this.ttlamtField;
            }
            set {
                this.ttlamtField = value;
                this.RaisePropertyChanged("Ttlamt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsdInvanSoToInvoicePostResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZsdInvoiceErr[] etErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZsdInvoiceErr[] EtError {
            get {
                return this.etErrorField;
            }
            set {
                this.etErrorField = value;
                this.RaisePropertyChanged("EtError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZsdInvanSoToInvoicePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePost ZsdInvanSoToInvoicePost;
        
        public ZsdInvanSoToInvoicePostRequest() {
        }
        
        public ZsdInvanSoToInvoicePostRequest(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePost ZsdInvanSoToInvoicePost) {
            this.ZsdInvanSoToInvoicePost = ZsdInvanSoToInvoicePost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZsdInvanSoToInvoicePostResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse ZsdInvanSoToInvoicePostResponse;
        
        public ZsdInvanSoToInvoicePostResponse1() {
        }
        
        public ZsdInvanSoToInvoicePostResponse1(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse ZsdInvanSoToInvoicePostResponse) {
            this.ZsdInvanSoToInvoicePostResponse = ZsdInvanSoToInvoicePostResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZSD_Invan_so_to_invoice_FGChannel : InCubeIntegration_BL.UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZSD_Invan_so_to_invoice_FGClient : System.ServiceModel.ClientBase<InCubeIntegration_BL.UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG>, InCubeIntegration_BL.UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG {
        
        public ZSD_Invan_so_to_invoice_FGClient() {
        }
        
        public ZSD_Invan_so_to_invoice_FGClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZSD_Invan_so_to_invoice_FGClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSD_Invan_so_to_invoice_FGClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSD_Invan_so_to_invoice_FGClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse1 InCubeIntegration_BL.UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG.ZsdInvanSoToInvoicePost(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest request) {
            return base.Channel.ZsdInvanSoToInvoicePost(request);
        }
        
        public InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse ZsdInvanSoToInvoicePost(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePost ZsdInvanSoToInvoicePost1) {
            InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest inValue = new InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest();
            inValue.ZsdInvanSoToInvoicePost = ZsdInvanSoToInvoicePost1;
            InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse1 retVal = ((InCubeIntegration_BL.UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG)(this)).ZsdInvanSoToInvoicePost(inValue);
            return retVal.ZsdInvanSoToInvoicePostResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse1> InCubeIntegration_BL.UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG.ZsdInvanSoToInvoicePostAsync(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest request) {
            return base.Channel.ZsdInvanSoToInvoicePostAsync(request);
        }
        
        public System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostResponse1> ZsdInvanSoToInvoicePostAsync(InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePost ZsdInvanSoToInvoicePost) {
            InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest inValue = new InCubeIntegration_BL.UFC_SalesReturns_WS.ZsdInvanSoToInvoicePostRequest();
            inValue.ZsdInvanSoToInvoicePost = ZsdInvanSoToInvoicePost;
            return ((InCubeIntegration_BL.UFC_SalesReturns_WS.ZSD_Invan_so_to_invoice_FG)(this)).ZsdInvanSoToInvoicePostAsync(inValue);
        }
    }
}
