//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCubeIntegration_BL.UFC_SalesOrder_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST")]
    public interface ZUFC_INVAN_SALE_ORD_POST {
        
        // CODEGEN: Generating message contract since the operation ZsdInvanSalesOrderCrWserv is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZUFC_INVAN_SALE_ORD_POST:ZsdInva" +
            "nSalesOrderCrWservRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse1 ZsdInvanSalesOrderCrWserv(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZUFC_INVAN_SALE_ORD_POST:ZsdInva" +
            "nSalesOrderCrWservRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse1> ZsdInvanSalesOrderCrWservAsync(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsdInvanSalesOrderCrWserv : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZinvanSoHeader[] etSoHeaderField;
        
        private ZinvanSoItem[] etSoItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinvanSoHeader[] EtSoHeader {
            get {
                return this.etSoHeaderField;
            }
            set {
                this.etSoHeaderField = value;
                this.RaisePropertyChanged("EtSoHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZinvanSoItem[] EtSoItem {
            get {
                return this.etSoItemField;
            }
            set {
                this.etSoItemField = value;
                this.RaisePropertyChanged("EtSoItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinvanSoHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ordernumberField;
        
        private string routekeyField;
        
        private string billtocodeField;
        
        private string shiptocodeField;
        
        private string orderdateField;
        
        private string deliverydateField;
        
        private string salesmancodeField;
        
        private string locationcodeField;
        
        private string routecodeField;
        
        private string lponumberField;
        
        private string orderamountField;
        
        private string headerdiscountField;
        
        private string isprocessedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Ordernumber {
            get {
                return this.ordernumberField;
            }
            set {
                this.ordernumberField = value;
                this.RaisePropertyChanged("Ordernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Routekey {
            get {
                return this.routekeyField;
            }
            set {
                this.routekeyField = value;
                this.RaisePropertyChanged("Routekey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Billtocode {
            get {
                return this.billtocodeField;
            }
            set {
                this.billtocodeField = value;
                this.RaisePropertyChanged("Billtocode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Shiptocode {
            get {
                return this.shiptocodeField;
            }
            set {
                this.shiptocodeField = value;
                this.RaisePropertyChanged("Shiptocode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Orderdate {
            get {
                return this.orderdateField;
            }
            set {
                this.orderdateField = value;
                this.RaisePropertyChanged("Orderdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Deliverydate {
            get {
                return this.deliverydateField;
            }
            set {
                this.deliverydateField = value;
                this.RaisePropertyChanged("Deliverydate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Salesmancode {
            get {
                return this.salesmancodeField;
            }
            set {
                this.salesmancodeField = value;
                this.RaisePropertyChanged("Salesmancode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Locationcode {
            get {
                return this.locationcodeField;
            }
            set {
                this.locationcodeField = value;
                this.RaisePropertyChanged("Locationcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Routecode {
            get {
                return this.routecodeField;
            }
            set {
                this.routecodeField = value;
                this.RaisePropertyChanged("Routecode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Lponumber {
            get {
                return this.lponumberField;
            }
            set {
                this.lponumberField = value;
                this.RaisePropertyChanged("Lponumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Orderamount {
            get {
                return this.orderamountField;
            }
            set {
                this.orderamountField = value;
                this.RaisePropertyChanged("Orderamount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Headerdiscount {
            get {
                return this.headerdiscountField;
            }
            set {
                this.headerdiscountField = value;
                this.RaisePropertyChanged("Headerdiscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Isprocessed {
            get {
                return this.isprocessedField;
            }
            set {
                this.isprocessedField = value;
                this.RaisePropertyChanged("Isprocessed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zreturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ordernumberField;
        
        private string typeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Ordernumber {
            get {
                return this.ordernumberField;
            }
            set {
                this.ordernumberField = value;
                this.RaisePropertyChanged("Ordernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZinvanSoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ordernumberField;
        
        private string billtocodeField;
        
        private string shiptocodeField;
        
        private string linenumberField;
        
        private string itemcodeField;
        
        private string uomField;
        
        private string quantityField;
        
        private string priceField;
        
        private string focindicatorField;
        
        private string itemdiscountField;
        
        private string totallineamountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Ordernumber {
            get {
                return this.ordernumberField;
            }
            set {
                this.ordernumberField = value;
                this.RaisePropertyChanged("Ordernumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Billtocode {
            get {
                return this.billtocodeField;
            }
            set {
                this.billtocodeField = value;
                this.RaisePropertyChanged("Billtocode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Shiptocode {
            get {
                return this.shiptocodeField;
            }
            set {
                this.shiptocodeField = value;
                this.RaisePropertyChanged("Shiptocode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Linenumber {
            get {
                return this.linenumberField;
            }
            set {
                this.linenumberField = value;
                this.RaisePropertyChanged("Linenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
                this.RaisePropertyChanged("Itemcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
                this.RaisePropertyChanged("Uom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Focindicator {
            get {
                return this.focindicatorField;
            }
            set {
                this.focindicatorField = value;
                this.RaisePropertyChanged("Focindicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Itemdiscount {
            get {
                return this.itemdiscountField;
            }
            set {
                this.itemdiscountField = value;
                this.RaisePropertyChanged("Itemdiscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Totallineamount {
            get {
                return this.totallineamountField;
            }
            set {
                this.totallineamountField = value;
                this.RaisePropertyChanged("Totallineamount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZsdInvanSalesOrderCrWservResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Zreturn[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zreturn[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZsdInvanSalesOrderCrWservRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWserv ZsdInvanSalesOrderCrWserv;
        
        public ZsdInvanSalesOrderCrWservRequest() {
        }
        
        public ZsdInvanSalesOrderCrWservRequest(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWserv ZsdInvanSalesOrderCrWserv) {
            this.ZsdInvanSalesOrderCrWserv = ZsdInvanSalesOrderCrWserv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZsdInvanSalesOrderCrWservResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse ZsdInvanSalesOrderCrWservResponse;
        
        public ZsdInvanSalesOrderCrWservResponse1() {
        }
        
        public ZsdInvanSalesOrderCrWservResponse1(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse ZsdInvanSalesOrderCrWservResponse) {
            this.ZsdInvanSalesOrderCrWservResponse = ZsdInvanSalesOrderCrWservResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZUFC_INVAN_SALE_ORD_POSTChannel : InCubeIntegration_BL.UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZUFC_INVAN_SALE_ORD_POSTClient : System.ServiceModel.ClientBase<InCubeIntegration_BL.UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST>, InCubeIntegration_BL.UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST {
        
        public ZUFC_INVAN_SALE_ORD_POSTClient() {
        }
        
        public ZUFC_INVAN_SALE_ORD_POSTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZUFC_INVAN_SALE_ORD_POSTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZUFC_INVAN_SALE_ORD_POSTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZUFC_INVAN_SALE_ORD_POSTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse1 InCubeIntegration_BL.UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST.ZsdInvanSalesOrderCrWserv(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest request) {
            return base.Channel.ZsdInvanSalesOrderCrWserv(request);
        }
        
        public InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse ZsdInvanSalesOrderCrWserv(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWserv ZsdInvanSalesOrderCrWserv1) {
            InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest inValue = new InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest();
            inValue.ZsdInvanSalesOrderCrWserv = ZsdInvanSalesOrderCrWserv1;
            InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse1 retVal = ((InCubeIntegration_BL.UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST)(this)).ZsdInvanSalesOrderCrWserv(inValue);
            return retVal.ZsdInvanSalesOrderCrWservResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse1> InCubeIntegration_BL.UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST.ZsdInvanSalesOrderCrWservAsync(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest request) {
            return base.Channel.ZsdInvanSalesOrderCrWservAsync(request);
        }
        
        public System.Threading.Tasks.Task<InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservResponse1> ZsdInvanSalesOrderCrWservAsync(InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWserv ZsdInvanSalesOrderCrWserv) {
            InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest inValue = new InCubeIntegration_BL.UFC_SalesOrder_WS.ZsdInvanSalesOrderCrWservRequest();
            inValue.ZsdInvanSalesOrderCrWserv = ZsdInvanSalesOrderCrWserv;
            return ((InCubeIntegration_BL.UFC_SalesOrder_WS.ZUFC_INVAN_SALE_ORD_POST)(this)).ZsdInvanSalesOrderCrWservAsync(inValue);
        }
    }
}
